BEGIN
BEGIN 
  DBMS_OUTPUT.PUT_LINE('ANNIVERSARY...');
  ISMA.PATIMES.SP_TIME2ANNVRSARY;
  COMMIT; 
END;

BEGIN 
  DBMS_OUTPUT.PUT_LINE('ELAPSED DAYS...');
  ISMA.PATIMES.SP_ELAPSEDDAYS;
  COMMIT; 
END; 

BEGIN 
DBMS_OUTPUT.PUT_LINE('ETWHR...');
  ISMA.PATIMES.WORKHR;
  COMMIT; 
END; 
END;
