--Ejecución SP's
GRANT EXECUTE ON CECO.SP_REPFINBANXICO TO USRWEB;
GRANT EXECUTE ON CECO.SP_REPFINBANXICO TO USRINF_BAZ;

GRANT EXECUTE ON CECO.SP_REPFINCNBV TO USRWEB;
GRANT EXECUTE ON CECO.SP_REPFINCNBV TO USRINF_BAZ;

--Ejecución paquetes
GRANT EXECUTE ON CECO.PA_MANBAN TO USRWEB;
GRANT EXECUTE ON CECO.PA_MANCNBV TO USRWEB;

GRANT EXECUTE ON CECO.PA_MANBAN TO USRINF_BAZ;
GRANT EXECUTE ON CECO.PA_MANCNBV TO USRINF_BAZ;

--Operaciones en tablas
GRANT SELECT,INSERT, UPDATE, DELETE ON CECO.TACCNE17_BANXICO TO USRINF_BAZ;
GRANT SELECT,INSERT, UPDATE, DELETE ON CECO.TACCNE18_CNBV TO USRINF_BAZ;
GRANT SELECT,INSERT, UPDATE, DELETE ON CECO.TACCNE19_COORD TO USRINF_BAZ;
GRANT SELECT,INSERT, UPDATE, DELETE ON CECO.TACCNE16_EXCEPCIONES TO USRINF_BAZ;
