CREATE USER USRCECINFPF IDENTIFIED BY NIO2390SOJ;
GRANT CONNECT TO USRCECINFPF;   --PERMISOS DE CONEXION  A LA DB AL USUARIO USRINFMICNEG
GRANT SELECT ON CECO.TACCBA012_MICNE TO USRCECINFPF;   --PERMISOS DE SELECT SOBRE EL OBJETO AL USUARIO USRINFMICNEG

DROP USER USRINFMICNEG CASCADE;   --BORRAR COMPLETAMENTE UN USR
DROP USER USRINFMICNEG;  --BORRAR UN USUARIO

